### ISSUE TITLE
VObject Eror on Centos 6

### ISSUE THREAD

**Issue by viable-hartman** [guewen/odoo-connector-magento-buildout#2]
Getting the following error doing bin/buildout, any help would be appreciated:

Getting distribution for 'vobject==0.8.1c'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 2147, in main
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 2133, in with_ei_usage
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 2150, in <lambda>
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 370, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 594, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 643, in install_item
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 833, in install_eggs
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1055, in build_and_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1040, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 63, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 109, in run
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 62, in runner
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 37, in _execfile
  File "/tmp/easy_install-t5RtSb/vobject-0.8.1c/setup.py", line 41
    """
       ^
SyntaxError: invalid syntax
An error occurred when trying to install vobject 0.8.1c. Look above this message for any errors that were output by easy_install.
/opt/odoo-connector-magento-buildout/eggs/anybox.recipe.openerp-1.8.4-py2.6.egg/anybox/recipe/openerp/base.py:276: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  missing = exc.message.split(os.linesep)[0].split()[-1]

**Comment by guewen** [comment]
Hi, I didn't tested on Centos.
Seems related to easy_install and vobject.
Can you try the following commands and say what happens:

```
cd /tmp
virtualenv test
. test/bin/activate
easy_install vobject 
```
